const PROGRAMS = {

  'MPI': {
    label: 'MPI', year: '1', field: 'MPI',
    semesters: [
      { label: 'Semester 1', subjects: [
        { label: 'Analyse I',                              coeff: 3,   ds: 'AnalyseDS',            ex: 'AnalyseEx',            tp: null },
        { label: 'Algèbre I',                              coeff: 3,   ds: 'AlgebreDS',             ex: 'AlgebreEx',            tp: null },
        { label: 'Algorithmique et Structures de Données I', coeff: 3, ds: 'Algo I DS',             ex: 'Algo I Ex',            tp: null },
        { label: 'Anglais',                                coeff: 1.5, ds: 'AnglaisDS',             ex: 'AnglaisEx',            tp: null },
        { label: 'Circuits Electriques',                   coeff: 4, ds: 'CircuitsDS',            ex: 'CircuitsEx',           tp: 'CircuitsTP' },
        { label: 'Droit',                                  coeff: 1.5, ds: 'DroitDS',               ex: 'DroitEx',              tp: null },
        { label: 'Electrostatique',                        coeff: 3, ds: 'ElectrostatiqueDS',     ex: 'ElectrostatiqueEx',    tp: 'ElectrostatiqueTP' },
        { label: 'Français',                               coeff: 1.5, ds: 'FrançaisDS',            ex: 'FrançaisEx',           tp: null },
        { label: 'Mécanique',                              coeff: 4, ds: 'MécaniqueDS',           ex: 'MécaniqueEx',          tp: null },
        { label: 'Optique',                                coeff: 3, ds: 'OptiqueDS',             ex: 'OptiqueEx',            tp: 'OptiqueTP' },
        { label: 'Programmation I',                        coeff: 2.5, ds: null,                    ex: 'ProgrammationEx',      tp: 'ProgrammationTP' },
      ]},
      { label: 'Semester 2', subjects: [
        { label: 'Analyse II',                             coeff: 3,   ds: 'Analyse2DS',            ex: 'Analyse2Ex',           tp: null },
        { label: 'Algèbre II',                             coeff: 3,   ds: 'Algebre2DS',            ex: 'Algebre2Ex',           tp: null },
        { label: 'Algorithmique et Structures de Données II', coeff: 3.5, ds: 'Algo II DS',           ex: 'Algo II Ex',           tp: null },
        { label: 'Anglais',                                coeff: 1.5, ds: 'Anglais2DS',            ex: 'Anglais2Ex',           tp: null },
        { label: 'Economie',                               coeff: 1.5, ds: 'EconomieDS',            ex: 'EconomieEx',           tp: null },
        { label: 'Electromagnétisme',                      coeff: 3.5,   ds: 'ElectromagnétismeDS',   ex: 'ElectromagnétismeEx',  tp: null },
        { label: 'Electronique',                           coeff: 3.5, ds: 'ElectroniqueDS',        ex: 'ElectroniqueEx',       tp: 'ElectroniqueTP' },
        { label: 'Français',                               coeff: 1.5, ds: 'Français2DS',           ex: 'Français2Ex',          tp: null },
        { label: 'Systèmes Logiques',                      coeff: 3.5, ds: 'Systèmes LogiquesDS',   ex: 'Systèmes LogiquesEx',  tp: 'Systèmes LogiquesTP' },
        { label: 'Thermodynamique',                        coeff: 3.5,   ds: 'ThermodynamiqueDS',     ex: 'ThermodynamiqueEx',    tp: 'ThermodynamiqueTP' },
        { label: 'Programmation II',                       coeff: 2, ds: null,                    ex: 'Programmation2Ex',     tp: 'Programmation2TP' },
      ]},
    ]
  },

  'CBA': {
    label: 'CBA', year: '1', field: 'CBA',
    semesters: [
      { label: 'Semester 1', subjects: [
        { label: 'Mathématiques',                          coeff: 3.5, ds: 'MathsDS',              ex: 'MathsEx',              tp: null },
        { label: 'Informatique 1',                         coeff: 3,   ds: 'Info1DS',              ex: 'Info1Ex',              tp: 'Info1TP' },
        { label: 'Electrostatique et Electromagnétisme',   coeff: 3,   ds: 'ElecStatDS',           ex: 'ElecStatEx',           tp: 'ElecStatTP' },
        { label: 'Optique géométrique',                    coeff: 3,   ds: 'OptiqueDS',            ex: 'OptiqueEx',            tp: 'OptiqueTP' },
        { label: 'Chimie Générale',                        coeff: 6,   ds: 'ChimieGenDS',          ex: 'ChimieGenEx',          tp: 'ChimieGenTP' },
        { label: 'Biologie cellulaire et moléculaire',     coeff: 5,   ds: 'BioCellDS',            ex: 'BioCellEx',            tp: 'BioCellTP' },
        { label: 'Génétique',                              coeff: 2,   ds: 'GenetiqueDS',          ex: 'GenetiqueEx',          tp: null },
        { label: 'Anglais',                                coeff: 1.5, ds: 'AnglaisDS',            ex: 'AnglaisEx',            tp: null },
        { label: 'Français',                               coeff: 1.5, ds: 'FrançaisDS',           ex: 'FrançaisEx',           tp: null },
        { label: "Introduction à l'économie",              coeff: 1.5, ds: 'EcoDS',                ex: 'EcoEx',                tp: null },
      ]},
      { label: 'Semester 2', subjects: [
        { label: 'Statistiques et Probabilités',           coeff: 3,   ds: 'StatsDS',              ex: 'StatsEx',              tp: null },
        { label: 'Informatique 2',                         coeff: 2,   ds: 'Info2DS',              ex: 'Info2Ex',              tp: 'Info2TP' },
        { label: 'Mécanique générale',                     coeff: 3,   ds: 'MecaGenDS',            ex: 'MecaGenEx',            tp: 'MecaGenTP' },
        { label: 'Mécanique des fluides',                  coeff: 3,   ds: 'MecaFluDS',            ex: 'MecaFluEx',            tp: 'MecaFluTP' },
        { label: "De l'atome à la molécule",               coeff: 3,   ds: 'AtomeDS',              ex: 'AtomeEx',              tp: null },
        { label: 'Réactivité NSP',                         coeff: 3,   ds: 'ReactNSPDS',           ex: 'ReactNSPEx',           tp: 'ReactNSPTP' },
        { label: 'Chimie organique',                       coeff: 4.5, ds: 'ChimieOrgDS',          ex: 'ChimieOrgEx',          tp: 'ChimieOrgTP' },
        { label: 'Biochimie structurale',                  coeff: 4,   ds: 'BiochimieDS',          ex: 'BiochimieEx',          tp: null },
        { label: 'Anglais',                                coeff: 1.5, ds: 'Anglais2DS',           ex: 'Anglais2Ex',           tp: null },
        { label: 'Français',                               coeff: 1.5, ds: 'Français2DS',          ex: 'Français2Ex',          tp: null },
        { label: 'Droit',                                  coeff: 1.5, ds: 'DroitDS',              ex: 'DroitEx',              tp: null },
      ]},
    ]
  },

  
  'GL2': {
    label: 'GL2', year: '2', field: 'GL',
    semesters: [
      { label: 'Semester 1', subjects: [
        { label: 'Architecture Des Ordinateurs',           coeff: 3,   ds: 'ADODS',                ex: 'ADOEx',                tp: null },
        { label: 'Anglais',                                coeff: 1.5, ds: 'AnglaisDS',            ex: 'AnglaisEx',            tp: null },
        { label: 'Bases de Données',                       coeff: 4,   ds: 'BDDDS',               ex: 'BDDEx',                tp: 'BDDTP' },
        { label: 'Français',                               coeff: 1.5, ds: 'FrançaisDS',           ex: 'FrançaisEx',           tp: null },
        { label: 'Gestion',                                coeff: 1.5, ds: 'GestionDS',            ex: 'GestionEx',            tp: null },
        { label: 'Programmation Orientée Objet',           coeff: 4,   ds: 'POODS',               ex: 'POOEx',                tp: 'POOTP' },
        { label: 'Probabilités et Statistiques',           coeff: 3,   ds: 'ProbaDS',              ex: 'ProbaEx',              tp: null },
        { label: 'Mathématiques du Signal',                coeff: 3,   ds: 'MDS',                  ex: 'MEx',                  tp: null },
        { label: 'Techniques de Transmission',             coeff: 3,   ds: 'TXDS',                ex: 'TXEx',                 tp: null },
        { label: "Systèmes d'Exploitation",                coeff: 3,   ds: 'SEDS',                ex: 'SEEx',                 tp: null },
        { label: 'C++',                                    coeff: 2,   ds: null,                   ex: 'CPPEx',                tp: 'CPPTP' },
        { label: 'Python',                                 coeff: 2,   ds: null,                   ex: 'PythonEx',             tp: 'PythonTP' },
      ]},
      { label: 'Semester 2', subjects: [
        { label: 'Algèbre',                                coeff: 3,   ds: 'AlgebreDS',            ex: 'AlgebreEx',            tp: null },
        { label: 'Analyse Mathématique',                   coeff: 3,   ds: 'AnalyseDS',            ex: 'AnalyseEx',            tp: null },
        { label: 'Architecture des Réseaux',               coeff: 3,   ds: 'RéseauxDS',            ex: 'RéseauxEx',            tp: 'RéseauxTP' },
        { label: 'Anglais',                                coeff: 1.5, ds: 'Anglais2DS',           ex: 'Anglais2Ex',           tp: null },
        { label: 'Comptabilité',                           coeff: 1.5, ds: 'ComptaDS',             ex: 'ComptaEx',             tp: null },
        { label: "Conception des Systèmes d'Information",  coeff: 4,   ds: 'ConceptionDS',         ex: 'ConceptionEx',         tp: 'ConceptionTP' },
        { label: 'Droit',                                  coeff: 1.5, ds: 'DroitDS',              ex: 'DroitEx',              tp: null },
        { label: 'SGBD',                                   coeff: 2.5, ds: 'SGBDDS',              ex: 'SGBDEx',               tp: 'SGBDTP' },
        { label: 'Java',                                   coeff: 2,   ds: null,                   ex: 'JavaEx',               tp: 'JavaTP' },
        { label: 'WEB',                                    coeff: 2,   ds: null,                   ex: 'WEBEx',                tp: 'WEBTP' },
        { label: 'Unix',                                   coeff: 2,   ds: null,                   ex: 'UnixEx',               tp: 'UnixTP' },
        { label: 'Applications Réparties',                 coeff: 2.5, ds: null,                   ex: 'ApplicationsRépartiesEx', tp: 'ApplicationsRépartiesTP' },
      ]},
    ]
  },

  'RT2': {
    label: 'RT2', year: '2', field: 'RT',
    semesters: [
      { label: 'Semester 1', subjects: [
        { label: 'Architecture Des Ordinateurs',           coeff: 2,   ds: 'ADODS',                ex: 'ADOEx',                tp: null },
        { label: 'Anglais',                                coeff: 1.5, ds: 'AnglaisDS',            ex: 'AnglaisEx',            tp: null },
        { label: 'Architecture Des Réseaux',               coeff: 3,   ds: 'ARDS',                 ex: 'AREx',                 tp: 'ARTP' },
        { label: 'Electronique',                           coeff: 3,   ds: 'ElectroniqueDS',        ex: 'ElectroniqueEx',       tp: 'ElectroniqueTP' },
        { label: 'Français',                               coeff: 1.5, ds: 'FrançaisDS',           ex: 'FrançaisEx',           tp: null },
        { label: 'Gestion',                                coeff: 1.5, ds: 'GestionDS',            ex: 'GestionEx',            tp: null },
        { label: 'Programmation Orientée Objet',           coeff: 3,   ds: 'POODS',               ex: 'POOEx',                tp: 'POOTP' },
        { label: 'Probabilités et Statistiques',           coeff: 3,   ds: 'ProbaDS',              ex: 'ProbaEx',              tp: null },
        { label: 'Mathématiques du Signal',                coeff: 3,   ds: 'MDS',                  ex: 'MEx',                  tp: null },
        { label: "Systèmes d'Exploitation",                coeff: 3,   ds: 'SEDS',                ex: 'SEEx',                 tp: null },
        { label: 'C++',                                    coeff: 2,   ds: null,                   ex: 'CPPEx',                tp: 'CPPTP' },
        { label: 'Python',                                 coeff: 2,   ds: null,                   ex: 'PythonEx',             tp: 'PythonTP' },
      ]},
      { label: 'Semester 2', subjects: [
        { label: 'Algèbre',                                coeff: 3,   ds: 'AlgebreDS',            ex: 'AlgebreEx',            tp: null },
        { label: 'Analyse Mathématique',                   coeff: 3,   ds: 'AnalyseDS',            ex: 'AnalyseEx',            tp: null },
        { label: 'Réseaux Locaux',                         coeff: 3,   ds: 'RéseauxDS',            ex: 'RéseauxEx',            tp: 'RéseauxTP' },
        { label: 'Anglais',                                coeff: 1.5, ds: 'Anglais2DS',           ex: 'Anglais2Ex',           tp: null },
        { label: 'Comptabilité',                           coeff: 1,   ds: 'ComptaDS',             ex: 'ComptaEx',             tp: null },
        { label: 'Ondes et Propagation',                   coeff: 2,   ds: 'OndesDS',              ex: 'OndesEx',              tp: null },
        { label: 'Droit',                                  coeff: 1,   ds: 'DroitDS',              ex: 'DroitEx',              tp: null },
        { label: 'Bases de Données',                       coeff: 3,   ds: 'BDDDS',               ex: 'BDDEx',                tp: 'BDDTP' },
        { label: 'Techniques de Transmission',             coeff: 2,   ds: 'TransmissionDS',       ex: 'TransmissionEx',       tp: null },
        { label: 'Télé-informatique',                      coeff: 3,   ds: 'TeleDS',               ex: 'TeleEx',               tp: 'TeleTP' },
        { label: 'Java',                                   coeff: 2,   ds: null,                   ex: 'JavaEx',               tp: 'JavaTP' },
        { label: 'WEB',                                    coeff: 2,   ds: null,                   ex: 'WEBEx',                tp: 'WEBTP' },
        { label: 'Unix',                                   coeff: 2,   ds: null,                   ex: 'UnixEx',               tp: 'UnixTP' },
      ]},
    ]
  },

  'IIA2': {
    label: 'IIA2', year: '2', field: 'IIA',
    semesters: [
      { label: 'Semester 1', subjects: [
        { label: 'Architecture Des Ordinateurs',           coeff: 2,   ds: 'ADODS',                ex: 'ADOEx',                tp: null },
        { label: 'Anglais',                                coeff: 1.5, ds: 'AnglaisDS',            ex: 'AnglaisEx',            tp: null },
        { label: 'Automatique',                            coeff: 3,   ds: 'AutoDS',               ex: 'AutoEx',               tp: 'AutoTP' },
        { label: 'Comptabilité',                           coeff: 1.5, ds: 'ComptabilitéDS',       ex: 'ComptabilitéEx',       tp: null },
        { label: 'Electronique',                           coeff: 3,   ds: 'ElectroniqueDS',        ex: 'ElectroniqueEx',       tp: 'ElectroniqueTP' },
        { label: 'Electrotechnique',                       coeff: 3.5, ds: 'ElectrotechniqueDS',   ex: 'ElectrotechniqueEx',   tp: 'ElectrotechniqueTP' },
        { label: 'Français',                               coeff: 1.5, ds: 'FrançaisDS',           ex: 'FrançaisEx',           tp: null },
        { label: 'Mécanique des Solides',                  coeff: 3,   ds: 'MSIDS',               ex: 'MSIEx',                tp: 'MSITP' },
        { label: 'Probabilités et Statistiques',           coeff: 3,   ds: 'ProbaDS',              ex: 'ProbaEx',              tp: null },
        { label: 'Mathématiques du Signal',                coeff: 3,   ds: 'MDS',                  ex: 'MEx',                  tp: null },
        { label: 'Programmation Orientée Objet',           coeff: 3,   ds: 'POODS',               ex: 'POOEx',                tp: 'POOTP' },
        { label: "Systèmes d'Exploitation",                coeff: 3.5, ds: 'SEDS',                ex: 'SEEx',                 tp: null },
      ]},
      { label: 'Semester 2', subjects: [
        { label: 'Algèbre',                                coeff: 3,   ds: 'AlgebreDS',            ex: 'AlgebreEx',            tp: null },
        { label: 'Analyse Mathématique',                   coeff: 3,   ds: 'AnalyseDS',            ex: 'AnalyseEx',            tp: null },
        { label: 'Anglais',                                coeff: 1.5, ds: 'Anglais2DS',           ex: 'Anglais2Ex',           tp: null },
        { label: 'Automatique Continue',                   coeff: 3,   ds: 'AutoConDS',            ex: 'AutoConEx',            tp: 'AutoConTP' },
        { label: 'Capteurs et Actionneurs',                coeff: 3,   ds: 'CapteursDS',           ex: 'CapteursEx',           tp: 'CapteursTP' },
        { label: 'Droit',                                  coeff: 1,   ds: 'DroitDS',              ex: 'DroitEx',              tp: null },
        { label: 'Electricité Industrielle',               coeff: 3,   ds: 'ElecDS',               ex: 'ElecEx',               tp: 'ElecTP' },
        { label: 'Electronique de Puissance',              coeff: 3,   ds: 'PuisDS',               ex: 'PuisEx',               tp: 'PuisTP' },
        { label: 'Gestion',                                coeff: 1,   ds: 'GestionDS',            ex: 'GestionEx',            tp: null },
        { label: 'Microprocesseurs et Interfaces',         coeff: 3,   ds: 'ProcDS',               ex: 'ProcEx',               tp: 'ProcTP' },
        { label: 'Réseaux',                                coeff: 2,   ds: 'RéseauxDS',            ex: 'RéseauxEx',            tp: null },
        { label: 'Traitement de Signal',                   coeff: 2,   ds: 'SignalDS',              ex: 'SignalEx',             tp: null },
      ]},
    ]
  },

  'IMI2': {
    label: 'IMI2', year: '2', field: 'IMI',
    semesters: [
      { label: 'Semester 1', subjects: [
        { label: 'Anglais',                                coeff: 1.5, ds: 'AnglaisDS',            ex: 'AnglaisEx',            tp: null },
        { label: 'Automatique',                            coeff: 3,   ds: 'AutoDS',               ex: 'AutoEx',               tp: 'AutoTP' },
        { label: 'Comptabilité',                           coeff: 1.5, ds: 'ComptabilitéDS',       ex: 'ComptabilitéEx',       tp: null },
        { label: 'Electronique',                           coeff: 3,   ds: 'ElectroniqueDS',        ex: 'ElectroniqueEx',       tp: 'ElectroniqueTP' },
        { label: 'Electrotechnique',                       coeff: 3,   ds: 'ElectrotechniqueDS',   ex: 'ElectrotechniqueEx',   tp: 'ElectrotechniqueTP' },
        { label: 'Français',                               coeff: 1.5, ds: 'FrançaisDS',           ex: 'FrançaisEx',           tp: null },
        { label: 'Incertitude des Mesures',                coeff: 3,   ds: 'IncertitudeDS',        ex: 'IncertitudeEx',        tp: 'IncertitudeTP' },
        { label: 'Mathématiques du Signal',                coeff: 3,   ds: 'MDS',                  ex: 'MEx',                  tp: null },
        { label: 'Méthodes et Moyens de Maintenance',      coeff: 3,   ds: 'MMMDS',               ex: 'MMMEx',                tp: null },
        { label: 'Microprocesseurs',                       coeff: 3,   ds: 'MicroprocDS',          ex: 'MicroprocEx',          tp: 'MicroprocTP' },
        { label: 'Probabilités et Statistiques',           coeff: 3,   ds: 'ProbaDS',              ex: 'ProbaEx',              tp: null },
        { label: "Systèmes d'Exploitation",                coeff: 3,   ds: 'SEDS',                ex: 'SEEx',                 tp: null },
      ]},
      { label: 'Semester 2', subjects: [
        { label: 'Algèbre',                                coeff: 3,   ds: 'AlgebreDS',            ex: 'AlgebreEx',            tp: null },
        { label: 'Analyse Mathématique',                   coeff: 3,   ds: 'AnalyseDS',            ex: 'AnalyseEx',            tp: null },
        { label: 'Anglais',                                coeff: 1.5, ds: 'Anglais2DS',           ex: 'Anglais2Ex',           tp: null },
        { label: 'Capteurs',                               coeff: 3,   ds: 'CapteursDS',           ex: 'CapteursEx',           tp: 'CapteursTP' },
        { label: 'Droit',                                  coeff: 1,   ds: 'DroitDS',              ex: 'DroitEx',              tp: null },
        { label: 'Electronique de Puissance',              coeff: 3,   ds: 'PuisDS',               ex: 'PuisEx',               tp: 'PuisTP' },
        { label: 'Gestion',                                coeff: 1,   ds: 'GestionDS',            ex: 'GestionEx',            tp: null },
        { label: 'Mécanique des Solides',                  coeff: 3,   ds: 'MDSDS',               ex: 'MDSEx',                tp: 'MDSTP' },
        { label: 'Ondes et Propagation',                   coeff: 2,   ds: 'OndesDS',              ex: 'OndesEx',              tp: null },
        { label: 'Programmation Orientée Objet',           coeff: 3,   ds: 'POODS',               ex: 'POOEx',                tp: 'POOTP' },
        { label: 'Technologie Mécanique',                  coeff: 3,   ds: 'TecMecDS',             ex: 'TecMecEx',             tp: 'TecMecTP' },
        { label: 'Traitement de Signal',                   coeff: 2,   ds: 'SignalDS',              ex: 'SignalEx',             tp: null },
      ]},
    ]
  },

  
  'CH2': {
    label: 'CH2', year: '2', field: 'CH',
    semesters: [
      { label: 'Semester 1', subjects: [
        { label: 'Mathématiques',                          coeff: 3,   ds: 'MathsDS',              ex: 'MathsEx',              tp: null },
        { label: 'Technologie chimique',                   coeff: 4,   ds: 'TechChimDS',           ex: 'TechChimEx',           tp: 'TechChimTP' },
        { label: 'Méthodes de séparation chromatographique', coeff: 4, ds: 'SepChromDS',           ex: 'SepChromEx',           tp: 'SepChromTP' },
        { label: "Méthodes spectroscopiques d'analyse",    coeff: 4,   ds: 'SpectroDS',            ex: 'SpectroEx',            tp: 'SpectroTP' },
        { label: 'Cinétique chimique',                     coeff: 4,   ds: 'CinetiqueDS',          ex: 'CinetiqueEx',          tp: 'CinetiqueTP' },
        { label: 'Equilibres des phases',                  coeff: 4,   ds: 'EquilibreDS',          ex: 'EquilibreEx',          tp: 'EquilibreTP' },
        { label: 'Synthèse organique',                     coeff: 4,   ds: 'SynthOrgDS',           ex: 'SynthOrgEx',           tp: 'SynthOrgTP' },
        { label: 'Anglais',                                coeff: 1.5, ds: 'AnglaisDS',            ex: 'AnglaisEx',            tp: null },
        { label: 'Gestion',                                coeff: 1.5, ds: 'GestionDS',            ex: 'GestionEx',            tp: null },
      ]},
      { label: 'Semester 2', subjects: [
        { label: 'Thermodynamique appliquée',              coeff: 4,   ds: 'ThermoDS',             ex: 'ThermoEx',             tp: 'ThermoTP' },
        { label: 'Mécanique des fluides',                  coeff: 4,   ds: 'MecaFluDS',            ex: 'MecaFluEx',            tp: 'MecaFluTP' },
        { label: 'Equilibres électrochimiques',            coeff: 4,   ds: 'EqElectroDS',          ex: 'EqElectroEx',          tp: 'EqElectroTP' },
        { label: 'Cinétique électrochimique',              coeff: 4.5, ds: 'CinElectroDS',         ex: 'CinElectroEx',         tp: 'CinElectroTP' },
        { label: 'Produits naturels et molécules du vivant', coeff: 4.5, ds: 'ProdNatDS',          ex: 'ProdNatEx',            tp: 'ProdNatTP' },
        { label: 'Physicochimie analytique',               coeff: 4,   ds: null,                   ex: 'PhysicoAnaEx',         tp: 'PhysicoAnaTP' },
        { label: 'Anglais',                                coeff: 1.5, ds: 'Anglais2DS',           ex: 'Anglais2Ex',           tp: null },
        { label: 'Français',                               coeff: 1.5, ds: 'Français2DS',          ex: 'Français2Ex',          tp: null },
        { label: "Droit de l'Homme",                       coeff: 1,   ds: 'DroitDS',              ex: 'DroitEx',              tp: null },
        { label: 'Comptabilité',                           coeff: 1,   ds: 'ComptaDS',             ex: 'ComptaEx',             tp: null },
      ]},
    ]
  },

  'BIO2': {
    label: 'BIO2', year: '2', field: 'BIO',
    semesters: [
      { label: 'Semester 1', subjects: [
        { label: 'Mathématiques',                          coeff: 3,   ds: 'MathsDS',              ex: 'MathsEx',              tp: null },
        { label: 'Méthodes en biotechnologie',             coeff: 4,   ds: 'MethBioDS',            ex: 'MethBioEx',            tp: 'MethBioTP' },
        { label: 'Informatique industrielle',              coeff: 2.5, ds: 'InfoIndusDS',          ex: 'InfoIndusEx',          tp: 'InfoIndusTP' },
        { label: 'Microbiologie générale',                 coeff: 4,   ds: 'MicroGenDS',           ex: 'MicroGenEx',           tp: 'MicroGenTP' },
        { label: 'Microbiologie appliquée',                coeff: 3,   ds: 'MicroAppDS',           ex: 'MicroAppEx',           tp: 'MicroAppTP' },
        { label: 'Biochimie métabolique',                  coeff: 3.5, ds: 'BioMetabDS',           ex: 'BioMetabEx',           tp: 'BioMetabTP' },
        { label: 'Biochimie moléculaire',                  coeff: 2.5, ds: 'BioMolDS',             ex: 'BioMolEx',             tp: null },
        { label: 'Biologie et physiologie animales',       coeff: 4.5, ds: 'BioAnimDS',            ex: 'BioAnimEx',            tp: 'BioAnimTP' },
        { label: 'Anglais',                                coeff: 1.5, ds: 'AnglaisDS',            ex: 'AnglaisEx',            tp: null },
        { label: 'Comptabilité',                           coeff: 1.5, ds: 'ComptaDS',             ex: 'ComptaEx',             tp: null },
      ]},
      { label: 'Semester 2', subjects: [
        { label: 'Biologie végétale',                      coeff: 2.5, ds: 'BioVegDS',             ex: 'BioVegEx',             tp: 'BioVegTP' },
        { label: 'Physiologie végétale',                   coeff: 3,   ds: 'PhysioVegDS',          ex: 'PhysioVegEx',          tp: 'PhysioVegTP' },
        { label: 'Biochimie alimentaire',                  coeff: 3.5, ds: 'BioAlimDS',            ex: 'BioAlimEx',            tp: 'BioAlimTP' },
        { label: 'Génie alimentaire',                      coeff: 3,   ds: 'GenieAlimDS',          ex: 'GenieAlimEx',          tp: null },
        { label: 'Microbiologie industrielle et alimentaire', coeff: 4, ds: 'MicroIndusDS',        ex: 'MicroIndusEx',         tp: 'MicroIndusTP' },
        { label: 'Technologie immunologique',              coeff: 4,   ds: 'ImmunoDS',             ex: 'ImmunoEx',             tp: 'ImmunoTP' },
        { label: 'Analyses biochimiques',                  coeff: 3.5, ds: 'AnalyseBioDS',         ex: 'AnalyseBioEx',         tp: 'AnalyseBioTP' },
        { label: 'Froid alimentaire',                      coeff: 1.5, ds: 'FroidDS',              ex: 'FroidEx',              tp: null },
        { label: 'Anglais',                                coeff: 1.5, ds: 'Anglais2DS',           ex: 'Anglais2Ex',           tp: null },
        { label: 'Français',                               coeff: 1.5, ds: 'Français2DS',          ex: 'Français2Ex',          tp: null },
        { label: 'Gestion',                                coeff: 1,   ds: 'GestionDS',            ex: 'GestionEx',            tp: null },
        { label: "Droit de l'homme",                       coeff: 1,   ds: 'DroitDS',              ex: 'DroitEx',              tp: null },
      ]},
    ]
  },
  'GL3': {
  label: 'GL3', year: '3', field: 'GL',
  semesters: [
    { label: 'Semester 1', subjects: [
      { label: 'Recherche opérationnelle',                 coeff: 2.5, ds: 'S1_RechercheOpDS',   ex: 'S1_RechercheOpEx',   tp: 'S1_RechercheOpTP' },
      { label: 'Modélisation des systèmes',                coeff: 2,   ds: 'S1_ModelisationDS',   ex: 'S1_ModelisationEx',   tp: null },
      { label: 'Mathématiques Statistiques',               coeff: 3,   ds: 'S1_MathStatsDS',      ex: 'S1_MathStatsEx',      tp: null },
      { label: 'Logique',                                  coeff: 2.5, ds: 'S1_LogiqueDS',        ex: 'S1_LogiqueEx',        tp: null },
      { label: 'Complexité des algorithmes',               coeff: 2.5, ds: 'S1_ComplexiteDS',     ex: 'S1_ComplexiteEx',     tp: null },
      { label: 'Architectures matérielles et prog. bas niveau', coeff: 2.5, ds: 'S1_ArchMatDS',   ex: 'S1_ArchMatEx',       tp: 'S1_ArchMatTP' },
      { label: 'Unix : Administration système et réseau',  coeff: 2.5, ds: null,                   ex: 'S1_UnixEx',           tp: 'S1_UnixTP' },
      { label: 'Ingénierie des Protocoles',                coeff: 2.5, ds: 'S1_IngProtoDS',       ex: 'S1_IngProtoEx',       tp: 'S1_IngProtoTP' },
      { label: 'Frameworks de développement',              coeff: 2.5, ds: null,                   ex: 'S1_FrameworkEx',      tp: 'S1_FrameworkTP' },
      { label: 'Analyse et Conception des Logiciels',      coeff: 2.5, ds: 'S1_ACLDS',            ex: 'S1_ACLEx',            tp: 'S1_ACLTP' },
      { label: 'Anglais',                                  coeff: 1.5, ds: 'S1_AnglaisDS',        ex: 'S1_AnglaisEx',        tp: null },
      { label: 'Arabe',                                    coeff: 1,   ds: 'S1_ArabeDS',          ex: 'S1_ArabeEx',          tp: null },
      { label: 'Théorie des organisations',                coeff: 1,   ds: 'S1_TheoOrgDS',        ex: 'S1_TheoOrgEx',        tp: null },
      { label: 'Français',                                 coeff: 1.5, ds: null,                   ex: 'S1_FrancaisEx',       tp: null },
      { label: 'Communication dans l\'entreprise',         coeff: 1,   ds: null,                   ex: 'S1_CommEntEx',        tp: null },
    ]},
    { label: 'Semester 2', subjects: [
      { label: 'Analyse numérique',                        coeff: 2,   ds: 'S2_AnaNumDS',         ex: 'S2_AnaNumEx',         tp: null },
      { label: 'Optimisation appliquée',                   coeff: 2,   ds: 'S2_OptimDS',           ex: 'S2_OptimEx',           tp: null },
      { label: 'Analyse des données',                      coeff: 2.5, ds: 'S2_AnaDonneesDS',     ex: 'S2_AnaDonneesEx',     tp: 'S2_AnaDonneesTP' },
      { label: 'Programmation logique',                    coeff: 3,   ds: 'S2_ProgLogDS',        ex: 'S2_ProgLogEx',        tp: 'S2_ProgLogTP' },
      { label: 'Algorithmique avancée',                    coeff: 2.5, ds: 'S2_AlgoAvDS',         ex: 'S2_AlgoAvEx',         tp: null },
      { label: 'Co-design',                                coeff: 2.5, ds: 'S2_CoDesignDS',       ex: 'S2_CoDesignEx',       tp: 'S2_CoDesignTP' },
      { label: 'Fondements des systèmes et Applications réparties', coeff: 2.5, ds: 'S2_FondSysDS', ex: 'S2_FondSysEx',       tp: 'S2_FondSysTP' },
      { label: 'Protocoles de communication Web-APIs',     coeff: 2.5, ds: null,                  ex: 'S2_WebProtoEx',        tp: 'S2_WebProtoTP' },
      { label: 'Méthodologies de Conception',              coeff: 2.5, ds: 'S2_MethoConcepDS',    ex: 'S2_MethoConcepEx',    tp: 'S2_MethoConcepTP' },
      { label: 'Bases de données non relationnelles',      coeff: 3,   ds: null,                  ex: 'S2_NoSQLEx',          tp: 'S2_NoSQLTP' },
      { label: 'Anglais',                                  coeff: 1.5, ds: 'S2_AnglaisDS',        ex: 'S2_AnglaisEx',        tp: null },
      { label: 'Marketing',                                coeff: 1.5, ds: 'S2_MarketingDS',      ex: 'S2_MarketingEx',      tp: null },
      { label: 'Projet Personnel Professionnel',           coeff: 2,   ds: null,                  ex: null,                  tp: 'S2_ProjetTP' },
    ]},
  ]
},
'RT3': {
  label: 'RT3', year: '3', field: 'RT',
  semesters: [
    { label: 'Semester 1', subjects: [
      { label: 'Optimisation non linéaire',                 coeff: 2,   ds: 'S1_OptimNonLinDS',   ex: 'S1_OptimNonLinEx',   tp: null },
      { label: 'Recherche Opérationnelle et théorie des graphes', coeff: 2.5, ds: null,                ex: 'S2_RechercheOpEx',   tp: 'S2_RechercheOpTP' }, // FIXED: ds: null
      { label: 'Statistiques pour l\'ingénieur',           coeff: 2,   ds: 'S1_StatsIngDS',       ex: 'S1_StatsIngEx',       tp: null },
      { label: 'UNIX : Administration système et réseau',  coeff: 3,   ds: null,                 ex: 'S1_UnixAdmEx',        tp: 'S1_UnixAdmTP' },
      { label: 'Analyse et Conception des Logiciels',      coeff: 3,   ds: 'S1_ACLDS',           ex: 'S1_ACLEx',            tp: 'S1_ACLTP' },
      { label: 'Smart Device',                             coeff: 2.5, ds: 'S1_SmartDevDS',      ex: 'S1_SmartDevEx',       tp: 'S1_SmartDevTP' },
      { label: 'Circuit RF',                               coeff: 2.5, ds: 'S1_CircRFDS',        ex: 'S1_CircRFEx',         tp: 'S1_CircRFTP' },
      { label: 'Introduction aux systèmes de transmission numériques', coeff: 2.5, ds: 'S1_SysTransNumDS', ex: 'S1_SysTransNumEx', tp: 'S1_SysTransNumTP' },
      { label: 'Réseaux IP',                               coeff: 2.5, ds: 'S1_ResIPDS',         ex: 'S1_ResIPEx',          tp: 'S1_ResIPTP' },
      { label: 'Réseaux locaux sans fil',                  coeff: 2.5, ds: 'S1_ResLocalDS',      ex: 'S1_ResLocalEx',       tp: 'S1_ResLocalTP' },
      { label: 'Anglais',                                  coeff: 1.5, ds: 'S1_AnglaisDS',       ex: 'S1_AnglaisEx',        tp: null },
      { label: 'Arabe',                                    coeff: 1,   ds: 'S1_ArabeDS',         ex: 'S1_ArabeEx',          tp: null },
      { label: 'Français',                                 coeff: 1.5, ds: null,                ex: 'S1_FrancaisEx',       tp: null },
      { label: 'Théorie des organisations',                coeff: 1,   ds: 'S1_TheoOrgDS',       ex: 'S1_TheoOrgEx',        tp: null },
      { label: 'Communication dans l\'entreprise',         coeff: 1,   ds: null,                ex: 'S1_CommEntEx',        tp: null },
    ]},
    { label: 'Semester 2', subjects: [
      { label: 'Analyse numérique matricielle',             coeff: 1.5, ds: null,                 ex: 'S1_AnaNumMatEx',     tp: 'S1_AnaNumMatTP' },
      { label: 'Analyse des données',                      coeff: 2.5, ds: 'S2_AnalyseDonneesDS', ex: 'S2_AnalyseDonneesEx', tp: 'S2_AnalyseDonneesTP' },
      { label: 'Processus stochastiques et files d\'attente', coeff: 2, ds: 'S2_ProcessStochDS', ex: 'S2_ProcessStochEx', tp: null },
      { label: 'Logique formelle',                         coeff: 2,   ds: 'S2_LogiqueFormDS',    ex: 'S2_LogiqueFormEx',    tp: null },
      { label: 'Administration de bases de données',       coeff: 2.5, ds: 'S2_AdminBDDS',       ex: 'S2_AdminBDEx',        tp: 'S2_AdminBDTP' },
      { label: 'Technologies de développement Java EE',    coeff: 2.5, ds: 'S2_JavaEEDS',        ex: 'S2_JavaEEEx',         tp: 'S2_JavaEETP' },
      { label: 'Signaux et systèmes',                      coeff: 2.5, ds: 'S2_SignauxSysDS',    ex: 'S2_SignauxSysEx',     tp: 'S2_SignauxSysTP' },
      { label: 'Réseaux radio-mobiles cellulaires',        coeff: 2,   ds: 'S2_ResRadioDS',      ex: 'S2_ResRadioEx',       tp: null },
      { label: 'Administration et surveillance des réseaux', coeff: 2.5, ds: 'S2_AdminResDS',    ex: 'S2_AdminResEx',       tp: 'S2_AdminResTP' },
      { label: 'Sécurité des réseaux',                     coeff: 2.5, ds: null,                 ex: 'S2_SecuriteResEx',    tp: 'S2_SecuriteResTP' },
      { label: 'Ingénierie des protocoles',                coeff: 1.5, ds: 'S2_IngProtoDS',      ex: 'S2_IngProtoEx',       tp: null },
      { label: 'Anglais',                                  coeff: 1.5, ds: 'S2_AnglaisDS',       ex: 'S2_AnglaisEx',        tp: null },
      { label: 'Marketing',                                coeff: 1.5, ds: 'S2_MarketingDS',     ex: 'S2_MarketingEx',      tp: null },
      { label: 'Projet Personnel Professionnel',           coeff: 2,   ds: null,                ex: null,                  tp: 'S2_ProjetTP' },
    ]},
  ]
},
'IIA3': {
  label: 'IIA3', year: '3', field: 'IIA',
  semesters: [
    { label: 'Semester 1', subjects: [
      { label: 'Mathématiques de l\'ingénieur',            coeff: 2,   ds: 'S1_MathIngDS',       ex: 'S1_MathIngEx',       tp: null },
      { label: 'Analyse numérique',                        coeff: 3,   ds: 'S1_AnaNumDS',        ex: 'S1_AnaNumEx',        tp: 'S1_AnaNumTP' },
      { label: 'Automatique échantillonnée',               coeff: 2.5, ds: 'S1_AutoEchDS',       ex: 'S1_AutoEchEx',       tp: 'S1_AutoEchTP' },
      { label: 'Traitement numérique du signal',           coeff: 2.5, ds: 'S1_TraitNumSigDS',   ex: 'S1_TraitNumSigEx',   tp: 'S1_TraitNumSigTP' },
      { label: 'Transmission de données',                  coeff: 2.5, ds: 'S1_TransDonneesDS',  ex: 'S1_TransDonneesEx',  tp: 'S1_TransDonneesTP' },
      { label: 'Fonctions électroniques',                  coeff: 2.5, ds: 'S1_FonctElecDS',     ex: 'S1_FonctElecEx',     tp: 'S1_FonctElecTP' },
      { label: 'Résistance des Matériaux (RDM)',           coeff: 3,   ds: 'S1_RDMDS',           ex: 'S1_RDMEx',           tp: 'S1_RDMTP' },
      { label: 'Installations fluidiques et thermiques',   coeff: 3,   ds: 'S1_InstFluidDS',     ex: 'S1_InstFluidEx',     tp: 'S1_InstFluidTP' },
      { label: 'Convertisseurs statiques',                 coeff: 3,   ds: 'S1_ConvStatDS',      ex: 'S1_ConvStatEx',      tp: 'S1_ConvStatTP' },
      { label: 'Anglais',                                  coeff: 1.5, ds: 'S1_AnglaisDS',       ex: 'S1_AnglaisEx',       tp: null },
      { label: 'Arabe',                                    coeff: 1,   ds: 'S1_ArabeDS',         ex: 'S1_ArabeEx',         tp: null },
      { label: 'Français',                                 coeff: 1.5, ds: null,                ex: 'S1_FrancaisEx',      tp: null },
      { label: 'Théorie des organisations',                coeff: 1,   ds: 'S1_TheoOrgDS',       ex: 'S1_TheoOrgEx',       tp: null },
      { label: 'Communication dans l\'entreprise',         coeff: 1,   ds: null,                ex: 'S1_CommEntEx',       tp: null },
    ]},
    { label: 'Semester 2', subjects: [
      { label: 'Recherche opérationnelle et Optimisation', coeff: 2.5, ds: 'S2_RechercheOpDS',   ex: 'S2_RechercheOpEx',   tp: 'S2_RechercheOpTP' },
      { label: 'Conception des systèmes mécaniques',       coeff: 2.5, ds: null,                ex: 'S2_ConcepSysMecEx',  tp: 'S2_ConcepSysMecTP' },
      { label: 'Management de la qualité et Performance industrielle', coeff: 2.5, ds: 'S2_ManagementQualDS', ex: 'S2_ManagementQualEx', tp: null },
      { label: 'Régulation industrielle',                  coeff: 2.5, ds: 'S2_RegulIndusDS',    ex: 'S2_RegulIndusEx',    tp: 'S2_RegulIndusTP' },
      { label: 'Modélisation Identification et Estimation', coeff: 2.5, ds: 'S2_ModelIdentDS',    ex: 'S2_ModelIdentEx',    tp: 'S2_ModelIdentTP' },
      { label: 'Automatismes industriels',                 coeff: 2.5, ds: 'S2_AutoIndusDS',     ex: 'S2_AutoIndusEx',     tp: 'S2_AutoIndusTP' },
      { label: 'Technologie d\'acquisition, commande et interfaçage', coeff: 2.5, ds: 'S2_TechAcqDS', ex: 'S2_TechAcqEx', tp: 'S2_TechAcqTP' },
      { label: 'Architecture avancée des processeurs',     coeff: 2.5, ds: 'S2_ArchProcDS',      ex: 'S2_ArchProcEx',      tp: 'S2_ArchProcTP' },
      { label: 'Bases de données',                         coeff: 2.5, ds: 'S2_BDDDS',           ex: 'S2_BDDEx',           tp: 'S2_BDDTP' },
      { label: 'Programmation C/C++',                      coeff: 2.5, ds: null,                ex: 'S2_CPPEx',           tp: 'S2_CPPTP' },
      { label: 'Anglais',                                  coeff: 1.5, ds: 'S2_AnglaisDS',       ex: 'S2_AnglaisEx',       tp: null },
      { label: 'Marketing',                                coeff: 1.5, ds: 'S2_MarketingDS',     ex: 'S2_MarketingEx',     tp: null },
      { label: 'Projet Personnel Professionnel',           coeff: 2,   ds: null,                ex: null,                  tp: 'S2_ProjetTP' },
    ]},
  ]
},
'IMI3': {
  label: 'IMI3', year: '3', field: 'IMI',
  semesters: [
    { label: 'Semester 1', subjects: [
      { label: 'RDM',                                          coeff: 2.5, ds: 'S1_RDMDS',          ex: 'S1_RDMEx',          tp: 'S1_RDMTP' },
      { label: 'Fiabilité des systèmes',                       coeff: 2,   ds: 'S1_FiabiliteDS',     ex: 'S1_FiabiliteEx',    tp: null },
      { label: 'Connaissance et surveillance des installations électriques', coeff: 2.5, ds: 'S1_ConnaissInstElecDS', ex: 'S1_ConnaissInstElecEx', tp: 'S1_ConnaissInstElecTP' },
      { label: 'Techniques d\'étalonnage',                     coeff: 2.5, ds: 'S1_TechEtalDS',      ex: 'S1_TechEtalEx',      tp: 'S1_TechEtalTP' },
      { label: 'Automatismes industriels',                     coeff: 2.5, ds: 'S1_AutoIndusDS',     ex: 'S1_AutoIndusEx',     tp: 'S1_AutoIndusTP' },
      { label: 'Conception des systèmes mécaniques',           coeff: 2.5, ds: 'S1_ConcepSysMecDS',  ex: 'S1_ConcepSysMecEx',  tp: 'S1_ConcepSysMecTP' },
      { label: 'Fonctions électroniques',                      coeff: 2.5, ds: 'S1_FonctElecDS',     ex: 'S1_FonctElecEx',     tp: 'S1_FonctElecTP' },
      { label: 'Analyse numérique',                            coeff: 2.5, ds: 'S1_AnaNumDS',        ex: 'S1_AnaNumEx',        tp: 'S1_AnaNumTP' },
      { label: 'Mathématiques de l\'ingénieur',                coeff: 3,   ds: 'S1_MathIngDS',       ex: 'S1_MathIngEx',       tp: null },
      { label: 'Bases de données',                             coeff: 2.5, ds: 'S1_BDDDS',           ex: 'S1_BDDEx',           tp: 'S1_BDDTP' },
      { label: 'Anglais',                                      coeff: 1.5, ds: 'S1_AnglaisDS',       ex: 'S1_AnglaisEx',       tp: null },
      { label: 'Français',                                     coeff: 1.5, ds: null,                ex: 'S1_FrancaisEx',      tp: null },
      { label: 'Théorie des organisations',                    coeff: 1,   ds: 'S1_TheoOrgDS',       ex: 'S1_TheoOrgEx',       tp: null },
      { label: 'Communication dans l\'entreprise',             coeff: 1,   ds: null,                ex: 'S1_CommEntEx',       tp: null },
    ]},
    { label: 'Semester 2', subjects: [
      { label: 'Thermique industrielle',                       coeff: 2.5, ds: 'S2_ThermIndusDS',    ex: 'S2_ThermIndusEx',    tp: 'S2_ThermIndusTP' },
      { label: 'Mécanique des fluides',                        coeff: 2.5, ds: 'S2_MecaFluDS',       ex: 'S2_MecaFluEx',       tp: 'S2_MecaFluTP' },
      { label: 'Thermodynamique appliquée',                    coeff: 2.5, ds: 'S2_ThermoAppDS',     ex: 'S2_ThermoAppEx',     tp: 'S2_ThermoAppTP' },
      { label: 'Tableau de bord de maintenance',               coeff: 1.5, ds: 'S2_TabBordDS',       ex: 'S2_TabBordEx',       tp: null },
      { label: 'Traitement numérique du signal',               coeff: 2.5, ds: 'S2_TraitNumSigDS',   ex: 'S2_TraitNumSigEx',   tp: 'S2_TraitNumSigTP' },
      { label: 'Micro-contrôleurs - DSP',                      coeff: 2.5, ds: 'S2_MicroDSPDS',      ex: 'S2_MicroDSPEx',      tp: 'S2_MicroDSPTP' },
      { label: 'Instrumentations optiques',                    coeff: 2.5, ds: 'S2_InstOptDS',       ex: 'S2_InstOptEx',       tp: 'S2_InstOptTP' },
      { label: 'Réseaux informatiques',                        coeff: 1.5, ds: 'S2_ResInfoDS',       ex: 'S2_ResInfoEx',       tp: null },
      { label: 'Gestion de production assistée par ordinateur (GPAO)', coeff: 3, ds: 'S2_GPAODS',      ex: 'S2_GPAOEx',          tp: 'S2_GPAOTP' },
      { label: 'Gestion de la maintenance assistée par ordinateur (GMAO)', coeff: 3, ds: 'S2_GMAODS', ex: 'S2_GMAOEx',          tp: 'S2_GMAOTP' },
      { label: 'Anglais',                                      coeff: 1.5, ds: 'S2_AnglaisDS',       ex: 'S2_AnglaisEx',       tp: null },
      { label: 'Arabe',                                        coeff: 1,   ds: 'S2_ArabeDS',         ex: 'S2_ArabeEx',         tp: null },
      { label: 'Marketing',                                    coeff: 1.5, ds: null,                ex: 'S2_MarketingEx',     tp: null },
      { label: 'Projet Personnel Professionnel',               coeff: 2,   ds: null,                ex: null,                  tp: 'S2_ProjetTP' },
    ]},
  ]
},
'CH3': {
  label: 'CH3', year: '3', field: 'CH',
  semesters: [
    { label: 'Semester 1', subjects: [
      { label: 'Thermodynamique chimique',                       coeff: 3.5, ds: null,                ex: 'S1_ThermoChimEx',    tp: 'S1_ThermoChimTP' },
      { label: 'Contrôle, Régulation, Automatisme',              coeff: 3.5, ds: null,                ex: 'S1_ControleRegulEx', tp: 'S1_ControleRegulTP' },
      { label: 'Mathématiques de l\'ingénieur',                  coeff: 3,   ds: 'S1_MathIngDS',       ex: 'S1_MathIngEx',       tp: null },
      { label: 'Génie chimique III',                             coeff: 4,   ds: null,                ex: 'S1_GenieChim3Ex',    tp: 'S1_GenieChim3TP' },
      { label: 'Chimie inorganique industrielle',                coeff: 2.5, ds: 'S1_ChimInorgDS',     ex: 'S1_ChimInorgEx',     tp: 'S1_ChimInorgTP' },
      { label: 'Hygiène et sécurité du travail',                 coeff: 1.5, ds: 'S1_HygieneSecurDS',  ex: 'S1_HygieneSecurEx',  tp: null },
      { label: 'Étude approfondie des mécanismes réactionnels',  coeff: 4,   ds: 'S1_EtudeMecReacDS',  ex: 'S1_EtudeMecReacEx',  tp: null },
      { label: 'Application de la chimie organique industrielle', coeff: 3,   ds: 'S1_AppliChimOrgDS',  ex: 'S1_AppliChimOrgEx',  tp: 'S1_AppliChimOrgTP' },
      { label: 'Anglais',                                        coeff: 1.5, ds: 'S1_AnglaisDS',       ex: 'S1_AnglaisEx',       tp: null },
      { label: 'Théorie des organisations',                      coeff: 1,   ds: 'S1_TheoOrgDS',       ex: 'S1_TheoOrgEx',       tp: null },
      { label: 'Français',                                       coeff: 1.5, ds: null,                ex: 'S1_FrancaisEx',      tp: null },
      { label: 'Communication dans l\'entreprise',               coeff: 1,   ds: null,                ex: 'S1_CommEntEx',       tp: null },
    ]},
    { label: 'Semester 2', subjects: [
      { label: 'Méthodes numériques',                            coeff: 2,   ds: 'S2_MethNumDS',       ex: 'S2_MethNumEx',       tp: 'S2_MethNumTP' },
      { label: 'Automatisation, régulation, capteurs',           coeff: 2.5, ds: 'S2_AutoRegulCaptDS', ex: 'S2_AutoRegulCaptEx', tp: 'S2_AutoRegulCaptTP' },
      { label: 'Optimisation des procédés',                      coeff: 3,   ds: 'S2_OptimProcDS',     ex: 'S2_OptimProcEx',     tp: null },
      { label: 'Traitement des eaux',                            coeff: 2.5, ds: null,                ex: 'S2_TraitEauxEx',    tp: 'S2_TraitEauxTP' },
      { label: 'Electrochimie industrielle',                     coeff: 3,   ds: 'S2_ElectroIndusDS',  ex: 'S2_ElectroIndusEx',  tp: 'S2_ElectroIndusTP' },
      { label: 'Gestion et traitement des déchets',              coeff: 2.5, ds: 'S2_GestDechetsDS',   ex: 'S2_GestDechetsEx',   tp: 'S2_GestDechetsTP' },
      { label: 'Stratégie de synthèse et Rétrosynthèse organique', coeff: 3, ds: 'S2_StrategieSynthDS', ex: 'S2_StrategieSynthEx', tp: 'S2_StrategieSynthTP' },
      { label: 'Etats de la matière',                            coeff: 3,   ds: 'S2_EtatsMatDS',      ex: 'S2_EtatsMatEx',      tp: 'S2_EtatsMatTP' },
      { label: 'Méthodes séparatives et Miniaturisation',        coeff: 2.5, ds: 'S2_MethSepDS',       ex: 'S2_MethSepEx',       tp: 'S2_MethSepTP' },
      { label: 'Anglais',                                        coeff: 1.5, ds: 'S2_AnglaisDS',       ex: 'S2_AnglaisEx',       tp: null },
      { label: 'Arabe',                                          coeff: 1,   ds: 'S2_ArabeDS',         ex: 'S2_ArabeEx',         tp: null },
      { label: 'Marketing',                                      coeff: 1.5, ds: null,               ex: 'S2_MarketingEx',     tp: null },
      { label: 'Projet Personnel Professionnel',                 coeff: 2,   ds: null,               ex: null,                  tp: 'S2_ProjetTP' },
    ]},
  ]
},
'BIO3': {
  label: 'BIO3', year: '3', field: 'BIO',
  semesters: [
    { label: 'Semester 1', subjects: [
      { label: 'Analyses chimiques',                            coeff: 2.5, ds: 'S1_AnalyseChimDS',    ex: 'S1_AnalyseChimEx',    tp: 'S1_AnalyseChimTP' },
      { label: 'Chimie organique industrielle',                 coeff: 2,   ds: 'S1_ChimieOrgIndDS',   ex: 'S1_ChimieOrgIndEx',   tp: null },
      { label: 'Biotechnologie végétale',                       coeff: 2.5, ds: 'S1_BioVegDS',          ex: 'S1_BioVegEx',         tp: 'S1_BioVegTP' },
      { label: 'Analyses physiques et spectroscopie',           coeff: 2.5, ds: 'S1_AnalysePhysSpecDS', ex: 'S1_AnalysePhysSpecEx', tp: 'S1_AnalysePhysSpecTP' },
      { label: 'Génie enzymatique',                             coeff: 3,   ds: 'S1_GenieEnzymDS',      ex: 'S1_GenieEnzymEx',     tp: 'S1_GenieEnzymTP' },
      { label: 'Analyse numérique',                             coeff: 2,   ds: 'S1_AnaNumDS',          ex: 'S1_AnaNumEx',         tp: null },
      { label: 'Modélisation et simulation des bioprocédés',    coeff: 2.5, ds: null,                   ex: 'S1_ModelBioProcEx',   tp: 'S1_ModelBioProcTP' },
      { label: 'Transfert de matière et de chaleur',            coeff: 3,   ds: 'S1_TransfertMChDS',    ex: 'S1_TransfertMChEx',    tp: null },
      { label: 'Thermodynamique et thermique',                  coeff: 2.5, ds: null,                   ex: 'S1_ThermoThermEx',     tp: null },
      { label: 'Mécanique des fluides et hydraulique',          coeff: 2.5, ds: 'S1_MecaFluHydDS',      ex: 'S1_MecaFluHydEx',     tp: 'S1_MecaFluHydTP' },
      { label: 'Anglais',                                       coeff: 1.5, ds: 'S1_AnglaisDS',         ex: 'S1_AnglaisEx',         tp: null },
      { label: 'Communication dans l\'entreprise',              coeff: 1,   ds: null,                   ex: 'S1_CommEntEx',         tp: null },
      { label: 'Théorie des organisations',                     coeff: 1,   ds: 'S1_TheoOrgDS',         ex: 'S1_TheoOrgEx',         tp: null },
      // Français is in S2 (see below)
    ]},
    { label: 'Semester 2', subjects: [
      { label: 'Biosécurité et bioéthique',                     coeff: 1.5, ds: 'S2_BioSecurEthDS',    ex: 'S2_BioSecurEthEx',    tp: null },
      { label: 'Génie génétique',                               coeff: 2.5, ds: 'S2_GenieGenetDS',     ex: 'S2_GenieGenetEx',     tp: 'S2_GenieGenetTP' },
      { label: 'Technologie microbienne',                       coeff: 2.5, ds: 'S2_TechMicrobDS',      ex: 'S2_TechMicrobEx',      tp: 'S2_TechMicrobTP' },
      { label: 'Biotechnologies moléculaires',                  coeff: 2.5, ds: 'S2_BioMolDS',          ex: 'S2_BioMolEx',          tp: 'S2_BioMolTP' },
      { label: 'Biotechnologie environnementale',               coeff: 3,   ds: 'S2_BioEnvDS',          ex: 'S2_BioEnvEx',          tp: null },
      { label: 'Pharmacologie moléculaire',                     coeff: 2.5, ds: 'S2_PharmacoMolDS',     ex: 'S2_PharmacoMolEx',     tp: null },
      { label: 'Immunologie appliquée',                         coeff: 2.5, ds: 'S2_ImmunoAppDS',       ex: 'S2_ImmunoAppEx',       tp: 'S2_ImmunoAppTP' },
      { label: 'Bio-statistiques',                              coeff: 2,   ds: 'S2_BioStatsDS',        ex: 'S2_BioStatsEx',        tp: null },
      { label: 'Génie de la biocatalyse',                       coeff: 2.5, ds: 'S2_GenieBioCatDS',     ex: 'S2_GenieBioCatEx',     tp: 'S2_GenieBioCatTP' },
      { label: 'Mécanique et résistance des matériaux',         coeff: 2.5, ds: 'S2_MecaResMatDS',      ex: 'S2_MecaResMatEx',      tp: null },
      { label: 'Français',                                      coeff: 1.5, ds: 'S2_FrancaisDS',        ex: 'S2_FrancaisEx',        tp: null },
      { label: 'Anglais',                                       coeff: 1.5, ds: 'S2_AnglaisDS',         ex: 'S2_AnglaisEx',         tp: null },
      { label: 'Arabe',                                         coeff: 1,   ds: 'S2_ArabeDS',           ex: 'S2_ArabeEx',           tp: null },
      { label: 'Marketing',                                     coeff: 1.5, ds: null,                   ex: 'S2_MarketingEx',       tp: null },
      { label: 'Projet Personnel Professionnel',                coeff: 2,   ds: null,                   ex: null,                   tp: 'S2_ProjetTP' },
    ]},
  ]
},
};
